### ISSUE TITLE
Software License?

### ISSUE THREAD

**Issue by quinnypig** [marekq/rss-lambda#3]
Howdy.

I'm about to do something similar / monstrous--I'd like to start with your version as a baseline, but there's no license assigned to the repository. Any chance you could slap a license into place for this so I can use it without getting my wrist slapped?

**Comment by marekq** [comment]
Hey Corey, 

I'd be honored and somewhat surprised if you were to pick this highly amateurish code for a project. I added the MIT-0 license which will bar our license auditors from chasing you down with pitchforks. If you would prefer a difference license, I have absolutely no issue changing it. 

On a more serious note - feel free to share any suggestions on how this code can be improved. I've been using it to scrape the various AWS blogs over RSS, which makes it somewhat easier to drink from the AWS firehose. The frontend of https://marek.rocks/ and https://beta.marek.rocks/ read directly from the same table as well in case you'd like to parse/show RSS feeds somehow. 

If you deploy the SAM app, it should out of the box start scraping the AWS blogs and put them into DynamoDB. The email sending part is one that I'm still refining a bit - I tried to use Lambda Destinations for that, but there may be a few bugs still here and there. 

Finally, I haven't tested much more than AWS RSS feeds (which may have somewhat different formatting to regular RSS), but it should be easy to extend this to anything else really. 

Happy to help further and please send my regards to Billie!

**Comment by weisisheng** [comment]
This is an insanely great reference architecture.  I look forward to studying it carefully.
